name: tests

on:
  - push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18
          - 20

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: 'main'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.2
        with:
          branch: gh-pages
          folder: .
